// Product data
const products = [
    {
        id: 1,
        name: "Rose Elegance",
        category: "floral",
        price: 89.99,
        image: "https://via.placeholder.com/250x200/FFB6C1/000000?text=Rose+Elegance",
        description: "A delicate floral fragrance with notes of rose and jasmine.",
        rating: 4.8,
        sold: 245
    },
    {
        id: 2,
        name: "Woody Essence",
        category: "woody",
        price: 79.99,
        image: "https://via.placeholder.com/250x200/8B4513/FFFFFF?text=Woody+Essence",
        description: "A warm woody scent with hints of sandalwood and cedar.",
        rating: 4.6,
        sold: 189
    },
    {
        id: 3,
        name: "Oriental Mystery",
        category: "oriental",
        price: 99.99,
        image: "https://via.placeholder.com/250x200/FFD700/000000?text=Oriental+Mystery",
        description: "An exotic oriental perfume with vanilla and spice notes.",
        rating: 4.9,
        sold: 312
    },
    {
        id: 4,
        name: "Fresh Breeze",
        category: "fresh",
        price: 69.99,
        image: "https://via.placeholder.com/250x200/00CED1/FFFFFF?text=Fresh+Breeze",
        description: "A refreshing citrus fragrance perfect for everyday wear.",
        rating: 4.4,
        sold: 156
    },
    {
        id: 5,
        name: "Lavender Dream",
        category: "floral",
        price: 84.99,
        image: "https://via.placeholder.com/250x200/E6E6FA/000000?text=Lavender+Dream",
        description: "A soothing lavender scent with calming properties.",
        rating: 4.7,
        sold: 203
    },
    {
        id: 6,
        name: "Amber Nights",
        category: "oriental",
        price: 109.99,
        image: "https://via.placeholder.com/250x200/FF6347/FFFFFF?text=Amber+Nights",
        description: "A rich amber fragrance for special occasions.",
        rating: 4.8,
        sold: 278
    },
    {
        id: 7,
        name: "Citrus Sunrise",
        category: "fresh",
        price: 74.99,
        image: "https://via.placeholder.com/250x200/FFA500/000000?text=Citrus+Sunrise",
        description: "Bright and energizing citrus notes with a hint of sweetness.",
        rating: 4.5,
        sold: 167
    },
    {
        id: 8,
        name: "Vanilla Bliss",
        category: "oriental",
        price: 94.99,
        image: "https://via.placeholder.com/250x200/D2691E/FFFFFF?text=Vanilla+Bliss",
        description: "Sweet vanilla warmth with subtle spice undertones.",
        rating: 4.7,
        sold: 234
    },
    {
        id: 9,
        name: "Ocean Waves",
        category: "fresh",
        price: 79.99,
        image: "https://via.placeholder.com/250x200/4682B4/FFFFFF?text=Ocean+Waves",
        description: "Fresh aquatic scent reminiscent of sea breeze.",
        rating: 4.3,
        sold: 145
    },
    {
        id: 10,
        name: "Jasmine Nights",
        category: "floral",
        price: 89.99,
        image: "https://via.placeholder.com/250x200/FFFFFF/000000?text=Jasmine+Nights",
        description: "Intoxicating jasmine bouquet with evening floral notes.",
        rating: 4.9,
        sold: 298
    },
    {
        id: 11,
        name: "Sandalwood Serenity",
        category: "woody",
        price: 104.99,
        image: "https://via.placeholder.com/250x200/DEB887/000000?text=Sandalwood+Serenity",
        description: "Deep, calming sandalwood with earthy undertones.",
        rating: 4.8,
        sold: 267
    },
    {
        id: 12,
        name: "Berry Temptation",
        category: "floral",
        price: 76.99,
        image: "https://via.placeholder.com/250x200/DC143C/FFFFFF?text=Berry+Temptation",
        description: "Juicy berry notes mixed with delicate florals.",
        rating: 4.6,
        sold: 189
    },
    {
        id: 13,
        name: "Spice Route",
        category: "oriental",
        price: 114.99,
        image: "https://via.placeholder.com/250x200/8B0000/FFFFFF?text=Spice+Route",
        description: "Exotic spice blend with oriental warmth.",
        rating: 4.9,
        sold: 345
    },
    {
        id: 14,
        name: "Pine Forest",
        category: "woody",
        price: 82.99,
        image: "https://via.placeholder.com/250x200/228B22/FFFFFF?text=Pine+Forest",
        description: "Fresh pine scent with woody earthiness.",
        rating: 4.4,
        sold: 178
    },
    {
        id: 15,
        name: "Gardenia Whisper",
        category: "floral",
        price: 91.99,
        image: "https://via.placeholder.com/250x200/F0E68C/000000?text=Gardenia+Whisper",
        description: "Soft gardenia petals with subtle sweetness.",
        rating: 4.7,
        sold: 223
    },
    {
        id: 16,
        name: "Musk Elegance",
        category: "oriental",
        price: 119.99,
        image: "https://via.placeholder.com/250x200/800080/FFFFFF?text=Musk+Elegance",
        description: "Sophisticated musk with oriental depth.",
        rating: 4.8,
        sold: 289
    },
    {
        id: 17,
        name: "Mint Refresh",
        category: "fresh",
        price: 67.99,
        image: "https://via.placeholder.com/250x200/00FF7F/000000?text=Mint+Refresh",
        description: "Cool mint freshness with herbal notes.",
        rating: 4.2,
        sold: 134
    },
    {
        id: 18,
        name: "Cherry Blossom",
        category: "floral",
        price: 86.99,
        image: "https://via.placeholder.com/250x200/FFB6C1/000000?text=Cherry+Blossom",
        description: "Delicate cherry blossom with spring florals.",
        rating: 4.6,
        sold: 201
    },
    {
        id: 19,
        name: "Cedar Wood",
        category: "woody",
        price: 96.99,
        image: "https://via.placeholder.com/250x200/A0522D/FFFFFF?text=Cedar+Wood",
        description: "Rich cedar wood with smoky undertones.",
        rating: 4.5,
        sold: 187
    },
    {
        id: 20,
        name: "Tropical Paradise",
        category: "fresh",
        price: 78.99,
        image: "https://via.placeholder.com/250x200/32CD32/FFFFFF?text=Tropical+Paradise",
        description: "Exotic tropical fruits with fresh greenery.",
        rating: 4.4,
        sold: 165
    },
    {
        id: 21,
        name: "Patchouli Dream",
        category: "woody",
        price: 88.99,
        image: "https://via.placeholder.com/250x200/8B4513/FFFFFF?text=Patchouli+Dream",
        description: "Earthy patchouli with woody depth.",
        rating: 4.7,
        sold: 212
    },
    {
        id: 22,
        name: "Lilac Fields",
        category: "floral",
        price: 83.99,
        image: "https://via.placeholder.com/250x200/C8A2C8/000000?text=Lilac+Fields",
        description: "Sweet lilac blossoms with floral elegance.",
        rating: 4.5,
        sold: 176
    },
    {
        id: 23,
        name: "Cinnamon Spice",
        category: "oriental",
        price: 97.99,
        image: "https://via.placeholder.com/250x200/D2691E/FFFFFF?text=Cinnamon+Spice",
        description: "Warm cinnamon spice with oriental richness.",
        rating: 4.8,
        sold: 256
    },
    {
        id: 24,
        name: "Aqua Marine",
        category: "fresh",
        price: 72.99,
        image: "https://via.placeholder.com/250x200/00CED1/FFFFFF?text=Aqua+Marine",
        description: "Fresh marine notes with aquatic coolness.",
        rating: 4.3,
        sold: 149
    },
    {
        id: 25,
        name: "Magnolia Bloom",
        category: "floral",
        price: 95.99,
        image: "https://via.placeholder.com/250x200/FFFACD/000000?text=Magnolia+Bloom",
        description: "Luxurious magnolia with creamy florals.",
        rating: 4.9,
        sold: 301
    },
    {
        id: 26,
        name: "Vetiver Essence",
        category: "woody",
        price: 101.99,
        image: "https://via.placeholder.com/250x200/696969/FFFFFF?text=Vetiver+Essence",
        description: "Sophisticated vetiver with smoky earthiness.",
        rating: 4.6,
        sold: 198
    },
    {
        id: 27,
        name: "Peony Garden",
        category: "floral",
        price: 87.99,
        image: "https://via.placeholder.com/250x200/FFC0CB/000000?text=Peony+Garden",
        description: "Romantic peony blossoms with floral charm.",
        rating: 4.7,
        sold: 215
    },
    {
        id: 28,
        name: "Ginger Zest",
        category: "oriental",
        price: 92.99,
        image: "https://via.placeholder.com/250x200/FF4500/FFFFFF?text=Ginger+Zest",
        description: "Spicy ginger warmth with oriental spice.",
        rating: 4.5,
        sold: 183
    },
    {
        id: 29,
        name: "Herbal Mist",
        category: "fresh",
        price: 71.99,
        image: "https://via.placeholder.com/250x200/9ACD32/000000?text=Herbal+Mist",
        description: "Fresh herbal blend with green notes.",
        rating: 4.2,
        sold: 127
    },
    {
        id: 30,
        name: "Tuberose Nights",
        category: "floral",
        price: 103.99,
        image: "https://via.placeholder.com/250x200/FFFFE0/000000?text=Tuberose+Nights",
        description: "Intense tuberose with nocturnal floral depth.",
        rating: 4.8,
        sold: 267
    },
    {
        id: 31,
        name: "Oakmoss Trail",
        category: "woody",
        price: 98.99,
        image: "https://via.placeholder.com/250x200/556B2F/FFFFFF?text=Oakmoss+Trail",
        description: "Forest oakmoss with earthy woody notes.",
        rating: 4.6,
        sold: 194
    },
    {
        id: 32,
        name: "Ylang Ylang",
        category: "floral",
        price: 89.99,
        image: "https://via.placeholder.com/250x200/FFF8DC/000000?text=Ylang+Ylang",
        description: "Exotic ylang ylang with tropical floral sweetness.",
        rating: 4.7,
        sold: 221
    },
    {
        id: 33,
        name: "Cardamom Heat",
        category: "oriental",
        price: 106.99,
        image: "https://via.placeholder.com/250x200/CD853F/FFFFFF?text=Cardamom+Heat",
        description: "Warm cardamom spice with oriental complexity.",
        rating: 4.9,
        sold: 312
    },
    {
        id: 34,
        name: "Green Tea",
        category: "fresh",
        price: 75.99,
        image: "https://via.placeholder.com/250x200/90EE90/000000?text=Green+Tea",
        description: "Fresh green tea with subtle herbal notes.",
        rating: 4.4,
        sold: 158
    },
    {
        id: 35,
        name: "Frangipani",
        category: "floral",
        price: 93.99,
        image: "https://via.placeholder.com/250x200/FFE4E1/000000?text=Frangipani",
        description: "Tropical frangipani with creamy floral elegance.",
        rating: 4.6,
        sold: 203
    },
    {
        id: 36,
        name: "Labdanum Gold",
        category: "oriental",
        price: 124.99,
        image: "https://via.placeholder.com/250x200/GoldenRod/000000?text=Labdanum+Gold",
        description: "Precious labdanum resin with golden oriental warmth.",
        rating: 5.0,
        sold: 378
    }
];

// Top 10 sold products (sorted by sold count)
const topSoldProducts = products.sort((a, b) => b.sold - a.sold).slice(0, 10);

// Translations
const translations = {
    en: {
        home: "Home",
        products: "Products",
        about: "About",
        contact: "Contact",
        login: "Login",
        register: "Register",
        logout: "Logout",
        welcome: "Welcome to Perfume Paradise",
        "hero-text": "Discover the finest fragrances from around the world",
        "shop-now": "Shop Now",
        "featured-products": "Featured Products",
        "top-ten-products": "Top 10 Products",
        search: "Search perfumes...",
        "all-categories": "All Categories",
        "shopping-cart": "Shopping Cart",
        total: "Total",
        checkout: "Checkout",
        "no-account": "Don't have an account?",
        "order-history": "Order History",
        "add-to-cart": "Add to Cart",
        "remove-from-cart": "Remove",
        "empty-cart": "Your cart is empty",
        "order-placed": "Order placed successfully!",
        "login-success": "Login successful!",
        "register-success": "Registration successful!",
        "logout-success": "Logged out successfully!",
        "invalid-credentials": "Invalid email or password",
        "user-exists": "User already exists",
        "fill-all-fields": "Please fill all fields",
        "view-order-history": "View Order History"
    },
    km: {
        home: "ទំព័រដើម",
        products: "ផលិតផល",
        about: "អំពីយើង",
        contact: "ទំនាក់ទំនង",
        login: "ចូល",
        register: "ចុះឈ្មោះ",
        logout: "ចាកចេញ",
        welcome: "សូមស្វាគមន៍មកកាន់ Perfume Paradise",
        "hero-text": "រកឃើញក្លិនក្រអូបល្អបំផុតពីជុំវិញពិភពលោក",
        "shop-now": "ទិញឥឡូវនេះ",
        "featured-products": "ផលិតផលពិសេស",
        "top-ten-products": "ផលិតផលលក់ដាច់បំផុត 10",
        search: "ស្វែងរកក្លិនក្រអូប...",
        "all-categories": "គ្រប់ប្រភេទ",
        "shopping-cart": "រទេះទិញទំនិញ",
        total: "សរុប",
        checkout: "បង់ប្រាក់",
        "no-account": "មិនទាន់មានគណនី?",
        "order-history": "ប្រវត្តិការបញ្ជាទិញ",
        "add-to-cart": "បញ្ចូលទៅក្នុងរទេះ",
        "remove-from-cart": "យកចេញ",
        "empty-cart": "រទេះរបស់អ្នកទទេ",
        "order-placed": "បញ្ជាទិញដោយជោគជ័យ!",
        "login-success": "ចូលដោយជោគជ័យ!",
        "register-success": "ចុះឈ្មោះដោយជោគជ័យ!",
        "logout-success": "ចាកចេញដោយជោគជ័យ!",
        "invalid-credentials": "អ៊ីមែលឬពាក្យសម្ងាត់មិនត្រឹមត្រូវ",
        "user-exists": "អ្នកប្រើប្រាស់មានរួចហើយ",
        "fill-all-fields": "សូមបំពេញគ្រប់ប្រអប់",
        "view-order-history": "មើលប្រវត្តិការបញ្ជាទិញ"
    },
    zh: {
        home: "首页",
        products: "产品",
        about: "关于我们",
        contact: "联系我们",
        login: "登录",
        register: "注册",
        logout: "登出",
        welcome: "欢迎来到香水天堂",
        "hero-text": "发现来自世界各地的最佳香水",
        "shop-now": "立即购买",
        "featured-products": "特色产品",
        "top-ten-products": "十大热销产品",
        search: "搜索香水...",
        "all-categories": "所有类别",
        "shopping-cart": "购物车",
        total: "总计",
        checkout: "结账",
        "no-account": "还没有账户？",
        "order-history": "订单历史",
        "add-to-cart": "添加到购物车",
        "remove-from-cart": "移除",
        "empty-cart": "您的购物车是空的",
        "order-placed": "订单提交成功！",
        "login-success": "登录成功！",
        "register-success": "注册成功！",
        "logout-success": "登出成功！",
        "invalid-credentials": "无效的邮箱或密码",
        "user-exists": "用户已存在",
        "fill-all-fields": "请填写所有字段",
        "view-order-history": "查看订单历史"
    }
};
